name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node test.js

      - name: Notify Discord
        if: always()   # luôn chạy dù test pass hay fail
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🔨 Build **{{ job.status }}**
            Repo: {{ github.repository }}
            Branch: {{ github.ref_name }}
            Commit: {{ github.sha }}
            Actor: {{ github.actor }}